### PR TITLE
Add EventSpot Components

### PR DESCRIPTION
**Pull request by zackkatz**
I've attempted to add full EventSpot functionality. 

I've implemented all the EventSpot API response objects as Components and have added inline documentation.

There are no tests written, but this is a solid start.

### CODE REVIEW

**Comment by zackkatz** [comment]
There are issues with the merge of the /development branch https://github.com/constantcontact/php-sdk/pull/131/commits/09495c57c48a71e438293a91151db152cfe3f10d

**Comment by WoogieNoogie** [comment]
This looks pretty great so far. I'll take a more thorough look later on this week.

**Comment by zackkatz** [comment]
@WoogieNoogie any chance to review?

**Comment by WoogieNoogie** [comment]
Thanks for the reminder, sorry for the wait, got caught up with some other things. I think this looks good, we'll get it merged into the development package. Do you need these to be accessible in a 1.x package?

**Comment by zackkatz** [comment]
I did, but didn't think 1.x was in development still, so I've moved on to 2.x.

**Comment by WoogieNoogie** [comment]
Sorry, that was my fault, too many numbers flying around. I meant 2.x - the PR is opened to the dev branch which is currently on an alpha version of 3.x, which requires PHP 5.5, due to a Guzzle update in dependencies. I'll get this merged in, but I may need to take some time to merge this into the 2.x line, for the differences in the Guzzle calls.

**Pull request merged**
